### ISSUE TITLE
Player drops are being removed/replaced, not just mobs.

### ISSUE THREAD

**Issue by SullyTheUnusual** [BlackJar72/MobDropStopper#1]
I'm trying to prevent iron and gold farms on my server, so I have IRON_INGOT replaced with PUMPKIN, and when players die, their iron ingots are dropping as pumpkins.  I thought this was supposed to only work for mobs?

**Comment by BlackJar72** [comment]
That is not something I thought of in the original context -- but it should not be hard to fix. Brb.

**Comment by BlackJar72** [comment]
Sorry for the inconvenience -- I guess I hadn't thought that through very well.  Version 1.1.0 well now only edit the drops of monsters / animals, not all entities as before.

**Comment by SullyTheUnusual** [comment]
Thank you so much for fixing it!  Your plugin is perfect for what I'm trying to do.  :)

**Comment by SullyTheUnusual** [comment]
Almost forgot...where do I get version 1.1.0?

**Comment by BlackJar72** [comment]
It should be I just uploaded it to BukkitDev -- so it should end up where the version was once they approve it.  In the mean time you can use this link:
http://www.mediafire.com/download/izk2m6ibh766qbp/MobDropStopper.jar

**Comment by SullyTheUnusual** [comment]
Thanks!
